# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58ef7643aff0a13d1e795488fcb80ea3fdf3e77ea1bb08cfa4320f2370eb3bbc79290d7d9c021f1028b3f50a6b075a3bd1186e0524a06360cda6fd92f844e430

test:
  secret_key_base: 95bab06feebe9bc8b9261d86a525f4f5f7ebd846f1f8477f09f200cf25b70a279a359f3c6d0bce04b54cb87a29fd7844144820e6132527a89f4acf1279f6a26d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
